"""Synthetic instance generator.

The generator is a deliverable, not a shortcut (PROJECT_BRIEF.md section 3).
It is fully deterministic: same seed in, byte-identical instance out. The
numbers we quote in the deck have to be reproducible on demand.

Phase 0 scope: 5 sections, 20 tasks, 7-day horizon, hardcoded traffic.
"""

from __future__ import annotations

import random
from datetime import date, datetime, timedelta

from src.models.catalogue import ActivitySpec, by_department
from src.generator.sections import archetype_of, build_sections
from src.models.calendar import REFERENCE_MONDAY
from src.models import (
    CrewCapacity,
    DataProvenance,
    Department,
    PlanningInstance,
    Section,
    Severity,
    SourceKind,
    Task,
    TrafficWindow,
)

PROVENANCE = (
    "SYNTHETIC. Generated by src/generator/synthetic.py. No Indian Railways "
    "operational data was used. Real TMS/SMMS/TDMS/COA feeds attach at the "
    "adapter layer (src/adapters). See ASSUMPTIONS.md."
)

# Day-of-week traffic multipliers, 0 = Monday. Sunday and Saturday run lighter
# passenger services. HAND-CHOSEN, see ASSUMPTIONS.md (A-04).
DOW_MULTIPLIER: tuple[float, ...] = (1.00, 1.00, 1.00, 1.00, 1.05, 0.90, 0.75)

# Freight is flagged on night hours of mixed-traffic sections, where goods
# paths are concentrated. See ASSUMPTIONS.md (A-04).
GOODS_HOURS = range(22, 24)
GOODS_HOURS_EARLY = range(0, 5)

# Crews a department can field per day, expressed as a share of the daily
# task load rather than a fixed count: a 40-section division does not run on
# the same establishment as a 5-section one. Tuned so capacity binds on some
# days without making the backlog impossible. PROVISIONAL, ASSUMPTIONS.md (A-06).
CREW_SHARE: dict[Department, float] = {
    Department.ENGG: 0.55,
    Department.TRD: 0.45,
    Department.SNT: 0.45,
}
MIN_CREWS_PER_DEPARTMENT = 2

# Departments are sampled uniformly, then an activity is drawn within the
# chosen department. Sampling activities directly from the flat catalogue
# skews the mix towards whichever department has most activity types listed
# (5 ENGG vs 4 S&T vs 3 TRD), which understated TRD badly in Phase 0.
# See ASSUMPTIONS.md (A-16).
DEPARTMENT_WEIGHTS: dict[Department, float] = {
    Department.ENGG: 0.45,  # Track work dominates real maintenance volume
    Department.TRD: 0.25,
    Department.SNT: 0.30,
}

# How the backlog is distributed. Roughly a quarter of pending work is already
# past its mandated date, which is what makes coordination urgent.
# See ASSUMPTIONS.md (A-07).
OVERDUE_FRACTION = 0.25
DUE_IN_HORIZON_FRACTION = 0.40


def _pick_severity(rng: random.Random, days_past_due: int) -> Severity:
    """Severity correlates with lateness, with noise.

    The correlation is deliberate: the Phase 3 criticality model needs real
    signal to learn, and in practice a defect left unattended degrades.
    """
    if days_past_due > 30:
        weights = [1, 2, 4, 6, 5]
    elif days_past_due > 0:
        weights = [2, 4, 5, 4, 2]
    else:
        weights = [5, 6, 4, 2, 1]
    return Severity(rng.choices([1, 2, 3, 4, 5], weights=weights, k=1)[0])


def _make_task(
    rng: random.Random,
    idx: int,
    section: Section,
    spec: ActivitySpec,
    horizon_start: date,
    horizon_days: int,
) -> Task:
    """Place one task on the due-date timeline.

    We choose where the task sits relative to its due date first, then work
    backwards to last_done_date. That way the backlog mix is controlled
    rather than emergent.
    """
    roll = rng.random()
    if roll < OVERDUE_FRACTION:
        # Already past due when the horizon opens.
        days_to_due = -rng.randint(1, 45)
    elif roll < OVERDUE_FRACTION + DUE_IN_HORIZON_FRACTION:
        # Falls due inside the planning window: must be scheduled.
        days_to_due = rng.randint(0, horizon_days)
    else:
        # Comfortably ahead: the optimiser may defer it.
        days_to_due = rng.randint(horizon_days + 1, horizon_days + 60)

    due_date = horizon_start + timedelta(days=days_to_due)
    last_done_date = due_date - timedelta(days=spec.interval_days)
    lo, hi = spec.duration_minutes_range
    crew_lo, crew_hi = spec.crew_range

    return Task(
        id=f"T{idx:03d}",
        department=spec.department,
        section_id=section.id,
        activity_type=spec.activity_type,
        # Round to 15-minute granularity: blocks are requested in quarter
        # hours, and it keeps the CP-SAT time grid small. ASSUMPTIONS.md (A-03).
        duration_minutes=15 * rng.randint(lo // 15, hi // 15),
        crew_required=rng.randint(crew_lo, crew_hi),
        last_done_date=last_done_date,
        interval_days=spec.interval_days,
        due_date=due_date,
        defect_severity=_pick_severity(rng, max(0, -days_to_due)),
        is_overdue=due_date < horizon_start,
        co_locatable=spec.co_locatable,
    )


def _build_traffic(
    sections: list[Section], horizon_start: date, horizon_days: int
) -> list[TrafficWindow]:
    """Materialise the per-section, per-day, per-hour traffic view.

    Section.traffic_density_profile is the baseline weekday shape; this
    applies the day-of-week multiplier to produce what the optimiser costs
    against.
    """
    windows: list[TrafficWindow] = []
    for section in sections:
        try:
            archetype = archetype_of(section.id)
        except KeyError:
            # A real, timetable-derived section. We have no freight data for
            # it: public passenger timetables do not carry goods paths, and
            # guessing them would be inventing traffic. Leave unflagged.
            archetype = None
        for day_offset in range(horizon_days):
            day = horizon_start + timedelta(days=day_offset)
            dow = day.weekday()
            multiplier = DOW_MULTIPLIER[dow]
            for hour in range(24):
                base = section.traffic_density_profile[hour]
                is_goods = archetype == "mixed_trunk" and (
                    hour in GOODS_HOURS or hour in GOODS_HOURS_EARLY
                )
                windows.append(
                    TrafficWindow(
                        section_id=section.id,
                        day=day,
                        hour_of_day=hour,
                        day_of_week=dow,
                        trains_per_hour=round(base * multiplier, 2),
                        is_goods_forecast=is_goods,
                    )
                )
    return windows


def _build_crew_capacity(
    rng: random.Random,
    horizon_start: date,
    horizon_days: int,
    n_tasks: int = 20,
) -> list[CrewCapacity]:
    capacity: list[CrewCapacity] = []
    tasks_per_day = max(1.0, n_tasks / max(1, horizon_days))
    for day_offset in range(horizon_days):
        day = horizon_start + timedelta(days=day_offset)
        for dept, share in CREW_SHARE.items():
            base = max(MIN_CREWS_PER_DEPARTMENT, round(tasks_per_day * share))
            crews = base + rng.randint(-1, 1)
            # Sunday: reduced establishment.
            if day.weekday() == 6:
                crews -= 1
            capacity.append(
                CrewCapacity(
                    department=dept, date=day,
                    available_crews=max(MIN_CREWS_PER_DEPARTMENT, crews),
                )
            )
    return capacity


def generate_tasks(
    rng: random.Random,
    sections: list[Section],
    n_tasks: int,
    horizon_start: date,
    horizon_days: int,
) -> list[Task]:
    """Generate a synthetic maintenance backlog against any section list.

    Split out from generate_instance so the same backlog logic can be laid
    over real, timetable-derived sections. See src/adapters/hybrid.py.
    """
    departments = list(DEPARTMENT_WEIGHTS)
    weights = [DEPARTMENT_WEIGHTS[d] for d in departments]
    catalogue_by_dept = {d: by_department(d) for d in departments}

    tasks: list[Task] = []
    for idx in range(1, n_tasks + 1):
        section = rng.choice(sections)
        dept = rng.choices(departments, weights=weights, k=1)[0]
        spec = rng.choice(catalogue_by_dept[dept])
        tasks.append(_make_task(rng, idx, section, spec, horizon_start, horizon_days))
    return tasks


def build_traffic(
    sections: list[Section], horizon_start: date, horizon_days: int
) -> list[TrafficWindow]:
    """Public wrapper: expand section profiles into per-day traffic windows."""
    return _build_traffic(sections, horizon_start, horizon_days)


def build_crew_capacity(
    rng: random.Random, horizon_start: date, horizon_days: int, n_tasks: int = 20
) -> list[CrewCapacity]:
    """Public wrapper for crew capacity generation."""
    return _build_crew_capacity(rng, horizon_start, horizon_days, n_tasks)


def generate_instance(
    seed: int = 42,
    n_tasks: int = 20,
    horizon_start: date = REFERENCE_MONDAY,
    horizon_days: int = 7,
    n_sections: int | None = 5,
) -> PlanningInstance:
    """Build one deterministic synthetic planning instance."""
    rng = random.Random(seed)

    sections = build_sections()
    if n_sections is not None:
        sections = sections[:n_sections]

    tasks = generate_tasks(rng, sections, n_tasks, horizon_start, horizon_days)

    instance = PlanningInstance(
        instance_id=f"phase0-s{seed}-{n_sections}sec-{n_tasks}task-{horizon_days}d",
        generated_at=datetime(2026, 1, 1, 0, 0, 0),  # fixed: keeps output byte-stable
        seed=seed,
        sources=DataProvenance(
            sections=SourceKind.SYNTHETIC,
            tasks=SourceKind.SYNTHETIC,
            traffic=SourceKind.SYNTHETIC,
            crew_capacity=SourceKind.SYNTHETIC,
            notes="Fully synthetic Phase 0 instance; no external data used.",
        ),
        provenance=PROVENANCE,
        horizon_start=horizon_start,
        horizon_days=horizon_days,
        sections=sections,
        tasks=tasks,
        traffic=_build_traffic(sections, horizon_start, horizon_days),
        crew_capacity=_build_crew_capacity(rng, horizon_start, horizon_days, n_tasks),
    )
    instance.validate_referential_integrity()
    return instance
