"""Unified data model for automatic block planning (SIH26027).

This is the single vocabulary every other module speaks. The adapter layer
(src/adapters) is responsible for translating department-specific feeds
(TMS / SMMS / TDMS / COA) into these types. Nothing downstream of the
adapter layer may reference a department-specific schema.

See PROJECT_BRIEF.md section 5.
"""

from __future__ import annotations

from datetime import date, datetime
from enum import Enum
from typing import Annotated

from pydantic import BaseModel, Field, computed_field, field_validator

HOURS_PER_DAY = 24


class Department(str, Enum):
    """The three departments that independently request blocks today."""

    ENGG = "ENGG"  # Permanent way: track, ballast, rails, bridges
    TRD = "TRD"  # Traction Distribution: overhead equipment
    SNT = "S&T"  # Signal & Telecommunications


class Severity(int, Enum):
    """Defect severity. Ordinal, 1 = cosmetic, 5 = safety-critical.

    Scale is our own construct: the three source systems each grade defects
    differently and we need one comparable axis. See ASSUMPTIONS.md (A-05).
    """

    COSMETIC = 1
    MINOR = 2
    MODERATE = 3
    SERIOUS = 4
    CRITICAL = 5


class SourceKind(str, Enum):
    """Where one component of a planning instance came from.

    Kept deliberately coarse. The point is that no part of the system can
    describe its data without saying which of these it is.
    """

    SYNTHETIC = "synthetic"  # Generated by us
    PUBLIC_TIMETABLE = "public_timetable"  # Published IR timetable, via aggregator
    PUBLISHED_MANUAL = "published_manual"  # IRPWM and equivalents
    LIVE_FEED = "live_feed"  # A real railway system. Nothing uses this yet.


class DataProvenance(BaseModel):
    """Per-component provenance for one planning instance.

    A single instance-wide `is_synthetic` boolean stopped being adequate the
    moment real timetable data entered the pipeline: traffic can be real
    while maintenance tasks remain generated. Recording provenance per
    component is what lets us state precisely which half of a headline number
    rests on real data. See PROJECT_BRIEF.md section 3.
    """

    sections: SourceKind
    tasks: SourceKind
    traffic: SourceKind
    crew_capacity: SourceKind
    notes: str = ""

    @property
    def components(self) -> dict[str, SourceKind]:
        return {
            "sections": self.sections,
            "tasks": self.tasks,
            "traffic": self.traffic,
            "crew_capacity": self.crew_capacity,
        }

    def summary_line(self) -> str:
        return "  ".join(f"{k}={v.value}" for k, v in self.components.items())


class Section(BaseModel):
    """A stretch of track between two points. The unit we schedule against."""

    id: str
    name: str
    division: str
    length_km: float = Field(gt=0)

    # Baseline weekday traffic shape: trains per hour, index 0..23 = hour of day.
    # TrafficWindow (below) is the materialised per-day view derived from this.
    traffic_density_profile: Annotated[list[float], Field(min_length=24, max_length=24)]

    @field_validator("traffic_density_profile")
    @classmethod
    def _non_negative(cls, v: list[float]) -> list[float]:
        if any(x < 0 for x in v):
            raise ValueError("traffic_density_profile entries must be >= 0")
        return v

    @computed_field  # type: ignore[prop-decorator]
    @property
    def peak_trains_per_hour(self) -> float:
        return max(self.traffic_density_profile)

    @computed_field  # type: ignore[prop-decorator]
    @property
    def daily_trains(self) -> float:
        return round(sum(self.traffic_density_profile), 2)


class Task(BaseModel):
    """One pending maintenance activity requiring a block on one section."""

    id: str
    department: Department
    section_id: str
    activity_type: str
    duration_minutes: int = Field(gt=0)
    crew_required: int = Field(ge=1)

    last_done_date: date
    interval_days: int = Field(gt=0)  # Mandated periodicity for this activity
    due_date: date
    defect_severity: Severity

    is_overdue: bool
    # True if this activity may share a block with another department's work
    # on the same section. Some activities cannot (e.g. work needing the
    # overhead line de-energised excludes simultaneous track machine work).
    co_locatable: bool = True

    @computed_field  # type: ignore[prop-decorator]
    @property
    def duration_hours(self) -> float:
        return round(self.duration_minutes / 60, 3)

    def days_overdue(self, as_of: date) -> int:
        """Positive if past due on `as_of`, else 0."""
        return max(0, (as_of - self.due_date).days)

    def days_to_due(self, as_of: date) -> int:
        """Signed: negative once overdue."""
        return (self.due_date - as_of).days


class TrafficWindow(BaseModel):
    """Expected train movements on one section, one hour, one day.

    This is what the optimiser costs a block against: blocking a section at
    03:00 loses far fewer train-hours than blocking it at 09:00.
    """

    section_id: str
    day: date
    hour_of_day: int = Field(ge=0, le=23)
    day_of_week: int = Field(ge=0, le=6)  # 0 = Monday
    trains_per_hour: float = Field(ge=0)
    is_goods_forecast: bool = False


class Block(BaseModel):
    """A granted window during which a section is out of service.

    One block may carry tasks from several departments — that co-location is
    the coordination win the whole project exists to demonstrate.
    """

    id: str
    section_id: str
    start: datetime
    end: datetime
    task_ids: list[str] = Field(min_length=1)
    departments: list[Department] = Field(min_length=1)

    @field_validator("end")
    @classmethod
    def _end_after_start(cls, v: datetime, info) -> datetime:
        start = info.data.get("start")
        if start is not None and v <= start:
            raise ValueError("block end must be after start")
        return v

    @computed_field  # type: ignore[prop-decorator]
    @property
    def duration_hours(self) -> float:
        return round((self.end - self.start).total_seconds() / 3600, 3)

    @computed_field  # type: ignore[prop-decorator]
    @property
    def is_shared(self) -> bool:
        """True if this block serves more than one department."""
        return len(set(self.departments)) > 1


class CrewCapacity(BaseModel):
    """How many crews a department can field on a given date."""

    department: Department
    date: date
    available_crews: int = Field(ge=0)


class PlanningInstance(BaseModel):
    """Everything the optimiser needs for one planning run.

    Carries its own provenance. `is_synthetic` is deliberately not optional
    and never defaults to False: no output of this system may present
    generated data as if it came from a live railway feed.
    See PROJECT_BRIEF.md section 3.
    """

    instance_id: str
    generated_at: datetime
    seed: int
    sources: DataProvenance
    provenance: str

    horizon_start: date
    horizon_days: int = Field(gt=0)

    sections: list[Section]
    tasks: list[Task]
    traffic: list[TrafficWindow]
    crew_capacity: list[CrewCapacity]

    @computed_field  # type: ignore[prop-decorator]
    @property
    def is_synthetic(self) -> bool:
        """True if ANY component is generated.

        Deliberately computed, not stored, and deliberately pessimistic: an
        instance with one synthetic component is a synthetic instance. This
        flag can never be set to False by accident, and partly-real data can
        never be presented as wholly real.
        """
        return any(
            kind == SourceKind.SYNTHETIC for kind in self.sources.components.values()
        )

    @computed_field  # type: ignore[prop-decorator]
    @property
    def is_fully_synthetic(self) -> bool:
        return all(
            kind == SourceKind.SYNTHETIC for kind in self.sources.components.values()
        )

    @computed_field  # type: ignore[prop-decorator]
    @property
    def horizon_end(self) -> date:
        from datetime import timedelta

        return self.horizon_start + timedelta(days=self.horizon_days)

    def section(self, section_id: str) -> Section:
        for s in self.sections:
            if s.id == section_id:
                return s
        raise KeyError(f"unknown section {section_id!r}")

    def tasks_for(self, section_id: str) -> list[Task]:
        return [t for t in self.tasks if t.section_id == section_id]

    def validate_referential_integrity(self) -> None:
        """Fail loudly on dangling references. Called by the generator."""
        ids = {s.id for s in self.sections}
        for t in self.tasks:
            if t.section_id not in ids:
                raise ValueError(f"task {t.id} references unknown section {t.section_id}")
        for w in self.traffic:
            if w.section_id not in ids:
                raise ValueError(f"traffic window references unknown section {w.section_id}")
        if len({t.id for t in self.tasks}) != len(self.tasks):
            raise ValueError("duplicate task ids")
        if len(ids) != len(self.sections):
            raise ValueError("duplicate section ids")
